// ABOUTME: Landing page for unauthenticated users
// ABOUTME: Showcases features and provides login/register CTAs

import { Link } from 'react-router-dom'
import { Brain, Zap, Trophy, Users, BookOpen, Target, ArrowRight } from 'lucide-react'

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Learning',
    description: 'Personalized questions generated by AI, verified for quality and accuracy.'
  },
  {
    icon: Target,
    title: 'Adaptive Mastery',
    description: 'Track your progress with probability-based mastery indices that adapt to your performance.'
  },
  {
    icon: BookOpen,
    title: 'Step-by-Step Hints',
    description: 'Get progressive hints when stuck, with AI solving individual steps without revealing the full solution.'
  },
  {
    icon: Zap,
    title: 'Smart Assignments',
    description: 'Receive personalized assignments based on your strengths, weaknesses, and learning patterns.'
  },
  {
    icon: Trophy,
    title: 'Compete & Win',
    description: 'Join city, state, and national level contests. Challenge friends to duels and 3v3 battles.'
  },
  {
    icon: Users,
    title: 'Community Learning',
    description: 'Marathons, leaderboards, and team competitions to keep you motivated.'
  }
]

export default function Landing() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-br from-primary-500 to-accent-500 rounded-xl flex items-center justify-center">
                <Brain className="w-6 h-6 text-white" />
              </div>
              <span className="text-2xl font-bold gradient-text">Brainwave</span>
            </div>
            <div className="flex items-center gap-4">
              <Link to="/login" className="text-gray-600 hover:text-gray-900 font-medium">
                Login
              </Link>
              <Link to="/register" className="btn-primary">
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Master Coding with
            <span className="block gradient-text">AI-Powered Learning</span>
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto mb-10">
            Personalized questions, adaptive mastery tracking, and gamified competitions.
            Learn smarter, not harder with Brainwave's intelligent tutoring system.
          </p>
          <div className="flex items-center justify-center gap-4">
            <Link to="/register" className="btn-primary flex items-center gap-2">
              Start Learning Free
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link to="/login" className="btn-secondary">
              I have an account
            </Link>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-8 max-w-2xl mx-auto mt-20">
          <div className="text-center">
            <div className="text-4xl font-bold gradient-text">10K+</div>
            <div className="text-gray-600">Questions</div>
          </div>
          <div className="text-center">
            <div className="text-4xl font-bold gradient-text">50+</div>
            <div className="text-gray-600">Topics</div>
          </div>
          <div className="text-center">
            <div className="text-4xl font-bold gradient-text">100K+</div>
            <div className="text-gray-600">Learners</div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-4">
            Everything You Need to Excel
          </h2>
          <p className="text-gray-600 text-center max-w-2xl mx-auto mb-16">
            Our AI-powered platform adapts to your learning style and helps you master
            programming concepts efficiently.
          </p>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature) => (
              <div key={feature.title} className="card hover:shadow-xl transition-shadow">
                <div className="w-12 h-12 bg-gradient-to-br from-primary-100 to-accent-100 rounded-xl flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-primary-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="bg-gradient-to-r from-primary-600 to-accent-600 rounded-3xl p-12 text-white">
            <h2 className="text-3xl font-bold mb-4">
              Ready to Level Up Your Coding Skills?
            </h2>
            <p className="text-lg opacity-90 mb-8">
              Join thousands of learners who are mastering programming with Brainwave.
            </p>
            <Link to="/register" className="inline-flex items-center gap-2 bg-white text-primary-600 px-8 py-4 rounded-lg font-semibold hover:bg-gray-100 transition-colors">
              Create Free Account
              <ArrowRight className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 bg-gradient-to-br from-primary-500 to-accent-500 rounded-lg flex items-center justify-center">
                <Brain className="w-5 h-5 text-white" />
              </div>
              <span className="text-white font-bold">Brainwave</span>
            </div>
            <p className="text-sm">
              &copy; 2026 Brainwave. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}
